# Generated by Django 6.0.2 on 2026-02-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.AutoField(db_column='거래id', primary_key=True, serialize=False, verbose_name='거래 식별자')),
                ('transaction_amount', models.DecimalField(db_column='거래금액', decimal_places=2, max_digits=15, null=True, verbose_name='거래 금액')),
                ('transaction_history', models.CharField(db_column='거래내역', max_length=255, null=True, verbose_name='거래 내역')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금')], db_column='입출금타입', max_length=10, null=True, verbose_name='입출금 타입')),
                ('transaction_method', models.CharField(choices=[('CASH', '현금'), ('BANK_TRANSFER', '계좌이체'), ('AUTO_TRANSFER', '자동이체'), ('CARD', '카드결제')], db_column='거래타입', max_length=20, null=True, verbose_name='거래 방식')),
                ('balance_after', models.DecimalField(db_column='거래후잔액', decimal_places=2, max_digits=15, null=True, verbose_name='거래 후 잔액')),
                ('transaction_at', models.DateTimeField(db_column='거래일시', null=True, verbose_name='거래 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='데이터 생성일')),
                ('account', models.ForeignKey(db_column='계좌id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='연결 계좌')),
            ],
            options={
                'verbose_name': '거래 내역',
                'verbose_name_plural': '거래 내역 목록',
                'db_table': 'transaction_history',
            },
        ),
    ]
