# Generated by Django 5.1.15 on 2026-02-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(choices=[('TOTAL_SPENDING', '총 지출'), ('TOTAL_INCOME', '총 수입')], max_length=30, verbose_name='분석대상')),
                ('type', models.CharField(choices=[('DAILY', '일간'), ('WEEKLY', '주간'), ('MONTHLY', '월간')], max_length=20, verbose_name='분석 기간 유형')),
                ('period_start', models.DateField(verbose_name='분석 시작일')),
                ('period_end', models.DateField(verbose_name='분석 종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='analysis/%Y/%m/', verbose_name='결과 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '분석',
                'verbose_name_plural': '분석 목록',
                'db_table': 'analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
