# Generated by Django 5.1.15 on 2026-02-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysis_id'),
        ('analysis', '0002_alter_analysis_options_alter_analysis_result_image'),
    ]

    operations = [
    ]
