# Generated by Django 5.1.15 on 2026-02-27 02:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(db_column='유저id', primary_key=True, serialize=False, verbose_name='유저 식별자')),
                ('user_email', models.EmailField(db_column='이메일', max_length=100, unique=True, verbose_name='유저 이메일')),
                ('user_name', models.CharField(db_column='이름', max_length=30, verbose_name='유저 이름')),
                ('user_nickname', models.CharField(db_column='닉네임', max_length=20, unique=True, verbose_name='유저 닉네임')),
                ('user_phone', models.CharField(db_column='전화번호', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='숫자만 입력하세요.', regex='^\\d+$')], verbose_name='유저 전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='생성일시', verbose_name='생성 일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
