# Generated by Django 6.0.2 on 2026-02-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='유저id', primary_key=True, serialize=False, verbose_name='유저 식별자')),
                ('user_email', models.EmailField(db_column='이메일', max_length=100, verbose_name='유저 이메일')),
                ('user_name', models.CharField(db_column='이름', max_length=30, verbose_name='유저 이름')),
                ('user_nickname', models.CharField(db_column='닉네임', max_length=20, unique=True, verbose_name='유저 닉네임')),
                ('user_pw', models.CharField(db_column='패스워드', max_length=255)),
                ('user_phone', models.CharField(db_column='전화번호', max_length=15, unique=True, verbose_name='유저 전화번호')),
                ('recent_login', models.DateTimeField(db_column='최근 로그인', null=True, verbose_name='최근 로그인 일시')),
                ('staff', models.BooleanField(db_column='스태프여부', default=False, verbose_name='스태프 여부')),
                ('admin', models.BooleanField(db_column='관리자여부', default=False, verbose_name='관리자 여부')),
                ('active', models.BooleanField(db_column='활성화여부', default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='생성일시', verbose_name='생성 일시')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
