# Generated by Django 6.0.2 on 2026-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, db_column='전화번호', max_length=15, null=True, unique=True, verbose_name='유저 전화번호'),
        ),
    ]
