# Generated by Django 6.0.2 on 2026-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(db_column='계좌id', primary_key=True, serialize=False, verbose_name='계좌 식별자')),
                ('bank_code', models.CharField(db_column='은행코드', max_length=3, verbose_name='은행 코드')),
                ('account_number', models.CharField(db_column='계좌번호', max_length=30, unique=True, verbose_name='계좌 번호')),
                ('account_type', models.CharField(choices=[('CHECKING', '입출금'), ('SAVINGS', '예금'), ('FIXED', '정기예금'), ('INSTALLMENT', '적금')], db_column='계좌유형', max_length=20, verbose_name='계좌 유형')),
                ('account_balance', models.DecimalField(db_column='계좌잔액', decimal_places=2, default=0.0, max_digits=15, verbose_name='계좌 잔액')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='생성일시', verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌 목록',
                'db_table': 'accounts',
            },
        ),
    ]
