name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: your-postgres-password
            POSTGRES_DB: project
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Packages & Libraries
      run: uv sync --dev

    - name: Run ruff (Linting)
      run: uv run ruff check .

    - name: Run Django Migration
      env:
          DEBUG: True
          SECRET_KEY: "ci-test-key"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: your-postgres-password
          POSTGRES_DB: project
          POSTGRES_HOST: localhost  # CI 환경에서는 localhost로 고정
          POSTGRES_PORT: 5432
      run: |
        uv run python manage.py makemigrations
        uv run python manage.py migrate

    - name: Run Django Tests
      env:
          DEBUG: True
          SECRET_KEY: "ci-test-key"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: your-postgres-password
          POSTGRES_DB: project
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
      run: uv run python manage.py test